### PR TITLE
[PR] Check and update AD data if needed when a profile is edited

### PR DESCRIPTION
**Pull request by philcable**

### CODE REVIEW

**Comment by philcable** [comment]
@jeremyfelt Let me know if this makes sense / #reviewmerge?

**Review by jeremyfelt — COMMENTED** [review]
This seems like a good place to check. One day it *could* be interesting to check it in the background rather than on page load. If AD was ever slow to respond, then it could be confusing to the editor.

For now - I think `admin_head` is an okay action to get it going on.

I do think a time check should be added, maybe in the post meta for the profile, that ensures AD is only checked once every X minutes. Otherwise we could end up pinging AD quite a bit.

Also, the data returned from `get_person_by_id()` is pretty unsanitized (straight from LDAP), and should be treated as such when storing.

**Comment by philcable** [comment]
@jeremyfelt Excellent points!

I almost think we could get away with 24 hours for the time check. Do you think that would be too much? Maybe just start with that and see how it goes?

**Review by jeremyfelt — APPROVED** [review]
Looks good! I think 24 hours is a good first choice. We can adapt if it seems wrong for some reason.

**Pull request merged**
